name = "email-generator-v2"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".open-next/worker"

[observability]
enabled = true

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://rameqnwlaldxwqqisrzq.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_Wv9W8ltwOoPFdwp5FhrPrQ_l1X8cfqh"
